### ISSUE TITLE
Inconsistent story tags and related bugs

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#109]
Font-sizes are inconsistent between large and small stories on iPad. Pictured below are tags that are displayed weirdly. @sreilly can you make sure we use a flexible width for tags, and that the padding on the left and right remain the same regardless of the contents?

iPhone:
![example-1](https://cloud.githubusercontent.com/assets/1379822/10024043/84fb6ebe-6155-11e5-9203-d5606104092e.jpg)

iPad:
![example-2](https://cloud.githubusercontent.com/assets/1379822/10024085/c8e2c88e-6155-11e5-9027-5bf752b468b4.jpg)

and another one for iPad:
![example-whatever](https://cloud.githubusercontent.com/assets/1379822/10024089/cb67d81a-6155-11e5-914c-ed16a3db9f47.jpg)

**Comment by sreilly** [comment]
Yes, I believe this one is already fixed.  Testflight is gummed up and not processing any of our uploads since this morning, so it's not yet apparent.

**Comment by thm** [comment]
Looks much better, the only thing you forgot to iron out is the differences in font-sizes

**Comment by sreilly** [comment]
@thm Yes, they are currently different sizes:

story title (normal size): 16pt
story title (small size): 14pt
category button (normal size): 13pt
category button (small size): 11pt

What should they be?

**Comment by thm** [comment]
Everything should be the same as on iPhone (11pt category tags), with the exception for large story-titles (24pt), for which there's more info at #86

**Comment by sreilly** [comment]
@thm doesn't #86 specify that the large titles are supposed to be 26pt?

**Comment by thm** [comment]
@sreilly sorry, yes, that will do

**Comment by sreilly** [comment]
@thm This one should also be all fixed with the update that is brewing now!

**Comment by thm** [comment]
@sreilly I'd like to make some small changes after seeing the new font-sizes, but I'll mark this issue complete so we can continue in #86. Thanks!
