### ISSUE TITLE
App crashes on startup (iOS 7.1.2)

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/ios-search-and-stories#166]
Reported on the forum, apparently version 6.0.5 is crashing on iOS 7.1.2

https://duck.co/forum/thread/16380/ver-6-bug-on-ipad-2

**Comment by sreilly** [comment]
Thanks for the report @tagawa  - this should be fixed in the current build (6.0.6) which is now waiting for app review.

**Comment by tagawa** [comment]
Thanks @sreilly - I've let the reporter know.

**Comment by speedbump101** [comment]
Unfortunately DDG 6.0.6 did not solve the crash issue. iPad 2, iOS 7.1.2. It crashes as soon as the logo screen terminates. Multiple reinstalls, and soft reboots haven't helped either.

**Comment by sreilly** [comment]
@speedbump101 would you mind installing a test build from our hockey account so that we can try and collect a crash report?  If this is ok can you send a message to sreilly@infinitekind.com and I'll send you an invite link?
