### ISSUE TITLE
Cancel tap when finger is moved

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#56]
When tapping a story (from the feed) or search (from favorites or recents), sliding, and then releasing, the item is activated regardless. We should cancel the tap once a finger is moved.

**Comment by sreilly** [comment]
This is now fixed in the just-pushed build.  I agree, it seems more natural for tapping outside of the popover to cancel it but still interact with the backing view.

**Comment by thm** [comment]
I think you meant #57 there, this one isn't actually fixed. However, upon closer look I'm marking this issue complete too, since it seems to be default behaviour. So, we might not want to change that!
